config/routes.rb
Rails.application.routes.draw do
    
  get 'welcome/index' 

  root 'welcome#index'

  get '/contact' => 'inquiries#new'

  get 'user/create'

  get 'user/user_params'

  get 'blog_posts/load_blog_posts'

  devise_for :users

  resources :comments

  resources :blog_posts

  resources :blogs

  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	belongs_to :blog
	belongs_to :user

	has_many   :comments
	
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    validates :subject, presence: true
    validates :article, presence: true
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  
  # before_filter :authenticate_user!
  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
      @blog_post = BlogPost.find(params[:id])
      @comments = @blog_post.comments
      @comment = Comment.new

      # require the ability to read blog posts
      # authorize! :read, @blog_post
  end

  def load_blog_posts
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
    @blog_post.author = current_user.first_name
    @blog_post.save
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    @blog_post.user_id = current_user.id
    @blog_post.author = current_user.first_name

    UserMailer.send_email(@blog_post).deliver

    respond_to do |format|
      if @blog_post.save

        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:subject, :article, :blog_id, :num_comments, :author, :avatar, :user_id)
    end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper

 def update_comments_count(blog_post_id)
	 #the blog_post we're updating
     blog_post = BlogPost.find(blog_post_id)

     #step 1: let's count the comments
     num_comments = blog_post.comments.count

     #step 2: update the blog_post table
     blog_post.num_comments = num_comments

     #set 3: save to table
     blog_post.save
	end

  def create
  	  @user = User.create( user_params )
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def user_params
  	  params.require(:user).permit(:avatar)
  end
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= f.text_field :subject, :class => "form-control", :placeholder => 'Title' %>
  </div><br/>
  <div class="field">
    by <%= current_user.first_name %>
  </div><br/>
  <div class="field">
    <label>Image (optional) </label>
    <%= f.file_field :avatar %>
</div><br/>
  <div class="field">
<!--     <%= f.label :article %><br>
 -->    <%= f.text_area :article, rows: 10, :class => "form-control" %>
  </div>
  

<!--   <div class="field">
    <%= f.label :blog_id %><br>
    <%= f.select :blog_id, Blog.all.collect {|blog| [ blog.blog_name, blog.id] }, :class => "form-control" %>
  </div> -->
  <br/>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
  			<div class="panel-body"><h1>Editing Post</h1>

				<%= render 'form' %>

				<%= link_to 'Show', @blog_post %> |
				<%= link_to 'Back', blog_posts_path %>
			</div>
		</div>
	</div>
</div>

app/views/blog_posts/index.html.erb
  <div class="row">
    <% @blog_posts.each do |blog_post| %>
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
              <% if blog_post.avatar_file_name != nil %>
                  <%= image_tag blog_post.avatar %>
              <% end %>
              <div class="caption">
              <h2><%= link_to blog_post.subject, blog_post %></h2>
              <p class="author">by <%= blog_post.author %></p>
              <div class="truncate"><%= blog_post.article.html_safe %></div> 
              <div class="row">
                <div class="col-xs-6"> <%= image_tag('icon-posted-time.png') %> <span class="date"><%= blog_post.created_at.strftime("%b %d, %Y") %></span></div>
                <div class="col-xs-6"><p><!-- Comments <span class="badge"> -->
                  <%= image_tag('icon-comment-count.png') %>
                  <% if blog_post.num_comments == nil %>
                    <span class="no-comments">No Comments</span>
                  <% elsif blog_post.num_comments == 1 %>
                      <span class="comments"><a href="/blog_posts/<%= blog_post.id %>/#comments">1 Comment</a></span>
                  <% else %>
                       <span class="comments"><a href="/blog_posts/<%= blog_post.id %>/#comments"><%= blog_post.num_comments %> Comments</a></span>
                  <% end %>
                </span>
                <!-- </span> -->
                </p></div>
              </div>
<!--               <%= link_to 'Read More...', blog_post, :class => "btn btn-primary" %>
 -->        <% if user_signed_in? %>
              <p><%= link_to 'Edit', edit_blog_post_path(blog_post) %>
              | <%= link_to 'Delete', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %>
              </p>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
</div>          

<br>

 <% if user_signed_in? %> <div align="center"><%= link_to 'New Blog post', new_blog_post_path, :class => "btn btn-danger" %></div> <<%end %>
<br/><br/>

app/views/blog_posts/load_blog_posts.html.erb
<h1>Load Blog Posts</h1>

<script type ="text/javascript">
	function loadBlogPosts() {

		$.getJSON("/blog_posts.json", function(data){
			// console.log(data)

			var html = "";

			$.each(data, function(index){

				html += "<b>" + data[index].subject + "</b><br/>";

			});
			// alert(html);
			$('#blog_posts a').html(html);
		});


	}
</script>

<div id="blog_posts" name="blog_posts">
		<a href="javascript:loadBlogPosts();">
			This is where the blog posts go
	   </a>
</div>

app/views/blog_posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
  			<div class="panel-body">
  				<h1>New Post</h1>

					<%= render 'form' %>

					<%= link_to 'Back', blog_posts_path %>
			</div>
		</div>
	</div>
</div>

app/views/blog_posts/show.html.erb
<% if notice != nil %>
	<p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
  			<div class="panel-body">
				<h2><%= @blog_post.subject %></h2>
				<p class="author">posted by <%= @blog_post.author %> on <%= @blog_post.created_at.strftime("%b %d, %Y") %></p>
				<% if @blog_post.avatar_file_name != nil %>
				  <div><%= image_tag @blog_post.avatar, width:'100%' %></div>
				  <br/>
				<% end %>
				<div><%= @blog_post.article.html_safe %></div>

				<p><%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
				<%= link_to 'Back', blog_posts_path %></p>

				<a name ="comments"></a>
				<!-- Show existing comments -->
				<h3> <% if @blog_post.num_comments == nil || @blog_post.num_comments == 0 %>
						No Comments
					 <% elsif @blog_post.num_comments == 1 %>
						<%= @blog_post.num_comments %> Comment
					<% else %>
						<%= @blog_post.num_comments %> Comments
					<% end %>
				</h3>

				<% if @blog_post.num_comments == nil || @blog_post.num_comments == 0 %>
					No comments.
				<% else %>
					<% @comments.each do |comment| %>
						<div class="panel panel-default">
							<div class="panel-body">
								<p><%= comment.comment%></p>
								<p><%= comment.created_at.strftime("%b %d, %Y") %></p>
								<p>by <%= comment.author%></p>
							</div>
						</div>
					<%end%>
				<% end %>

				<h3>Submit a Comment</h3>
				<%= form_for(@comment) do |f| %>
				  <% if @comment.errors.any? %>
				    <div id="error_explanation">
				      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
				      <ul>
				      	<% @comment.errors.full_messages.each do |message| %>
				        <li><%= message %></li>
				      <% end %>
				      </ul>
				    </div>
				  <% end %>

				  <div class="field">
				    <%= f.label :author %><br>
				    <%= f.text_field :author, :class => "form-control" %>
				  </div>
				  <div class="field">
				    <%= f.label :comment %><br>
				    <%= f.text_area :comment, :class => "form-control" %>
				  </div>
				   <%= f.hidden_field :blog_post_id, :value => @blog_post.id %>

				  <br/>
				  <div class="actions">
				    <%= f.submit :class => "btn btn-primary" %>
				  </div>
				<% end %>
			</div>
		</div>
	</div>
</div>