config/routes.rb
Rails.application.routes.draw do
    
  get 'welcome/index' 

  root 'welcome#index'

  get '/contact' => 'inquiries#new'

  get 'user/create'

  get 'user/user_params'

  get 'blog_posts/load_blog_posts'

  devise_for :users

  resources :comments

  resources :blog_posts

  resources :blogs

  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jaime's Awesome Portfolio</title>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><strong>Jaime's Rails Blog</strong></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <!-- <li><a href="/">Home</a></li>-->
        <li><%=link_to 'View All Posts', blog_posts_path %></li>
        <% if user_signed_in? %><li><%= link_to 'Add New Post', new_blog_post_path %></li><%end%>
        <!--<li><%=link_to 'Contact', contact_path %></li>-->
        <!--<li><%=link_to 'Blog', blogs_path %></li>-->
        <!-- <li><%=link_to 'Comments', comments_path %></li>-->       
      </ul>
      <% if user_signed_in? %>
           <p class="navbar-text navbar-right">Signed in as <a href="#" class="navbar-link"><%= current_user.first_name %> <%= current_user.last_name %></a></p>
           <%= link_to "Sign out",destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn navbar-right" %>
        <% else %>
           <a class="btn btn-default navbar-btn navbar-right" href="/users/sign_in">Sign in</a>
     <% end %>
  </div><!-- /.container-fluid -->
</nav>

<!-- <p style="background:grey;position:absolute;width:300px;height:100px;top:0;right:100px;">
<% if user_signed_in? %>
  You are logged in as <%= current_user.email %> |
  <%= link_to "Sign out",destroy_user_session_path, method: :delete, class: "button" %>
<% else %>
  <a href="/users/sign_up">Sign up</a> or <a href="/users/sign_in">Sign in</a> 
<% end %>
</p> 

<%= image_tag 'handstand.jpg' %>-->

<div class="container-fluid">
<%= yield %>
</div>

</body>

<script>
$(document).ready(function() {
    $('.truncate').succinct({
        size: 120
    });
});
</script>
</html>